package gui;

import jade.gui.GuiEvent;
import javax.swing.DefaultComboBoxModel;

public class AuctionGui extends javax.swing.JFrame {

    private final AuctionGuiAgent myAgent;
    
    /**
     * Creates new form AuctionGui
     */
    public AuctionGui(AuctionGuiAgent agent) {
        myAgent = agent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Agent2Combo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        estimate1 = new javax.swing.JTextField();
        estimate2 = new javax.swing.JTextField();
        estimate3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        FormatCombo = new javax.swing.JComboBox<>();
        StartButton = new javax.swing.JButton();
        Agent1Combo = new javax.swing.JComboBox<>();
        Agent3Combo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Agent5Combo = new javax.swing.JComboBox<>();
        Agent6Combo = new javax.swing.JComboBox<>();
        Agent4Combo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        estimate4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        estimate5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        estimate6 = new javax.swing.JTextField();
        interest1 = new javax.swing.JComboBox<>();
        interest2 = new javax.swing.JComboBox<>();
        interest3 = new javax.swing.JComboBox<>();
        interest4 = new javax.swing.JComboBox<>();
        interest5 = new javax.swing.JComboBox<>();
        interest6 = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bidder1");

        jLabel2.setText("Bidder2");

        jLabel3.setText("Bidder3");

        Agent2Combo.setModel(new DefaultComboBoxModel(EnglishStrategies));

        jLabel4.setText("Estimate");

        jLabel5.setText("Estimate");

        jLabel6.setText("Estimate");

        estimate1.setText("20");
        estimate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimate1ActionPerformed(evt);
            }
        });

        estimate2.setText("50");

        estimate3.setText("100");
        estimate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimate3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Auction Format");

        FormatCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Dutch", "Scottish", "First-Price", "Vickrey", "Combo" }));
        FormatCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormatComboActionPerformed(evt);
            }
        });

        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        Agent1Combo.setModel(new DefaultComboBoxModel(EnglishStrategies));

        Agent3Combo.setModel(new DefaultComboBoxModel(EnglishStrategies));

        jLabel8.setText("Bidder4");

        jLabel9.setText("Bidder5");

        jLabel10.setText("Bidder6");

        Agent5Combo.setModel(new DefaultComboBoxModel(EnglishStrategies));

        Agent6Combo.setModel(new DefaultComboBoxModel(EnglishStrategies));

        Agent4Combo.setModel(new DefaultComboBoxModel(EnglishStrategies));

        jLabel11.setText("Interest");

        jLabel12.setText("Interest");

        jLabel13.setText("Interest");

        jLabel14.setText("Interest");

        jLabel15.setText("Estimate");

        estimate4.setText("130");
        estimate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimate4ActionPerformed(evt);
            }
        });

        jLabel16.setText("Interest");

        jLabel17.setText("Estimate");

        estimate5.setText("160");
        estimate5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimate5ActionPerformed(evt);
            }
        });

        jLabel18.setText("Interest");

        jLabel19.setText("Estimate");

        estimate6.setText("200");
        estimate6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimate6ActionPerformed(evt);
            }
        });

        interest1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High" }));

        interest2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High" }));

        interest3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High" }));

        interest4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High" }));

        interest5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High" }));

        interest6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estimate4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(interest4, 0, 1, Short.MAX_VALUE)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Agent1Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estimate1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(interest1, 0, 1, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(Agent4Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FormatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Agent2Combo, 0, 122, Short.MAX_VALUE))
                                        .addGap(136, 136, 136))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(estimate2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                                    .addComponent(interest3, 0, 1, Short.MAX_VALUE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(estimate5))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                                    .addComponent(interest5, 0, 1, Short.MAX_VALUE)))
                                            .addComponent(Agent5Combo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Agent3Combo, javax.swing.GroupLayout.Alignment.LEADING, 0, 110, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(Agent6Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(estimate6))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel18)
                                                .addComponent(interest6, 0, 1, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(estimate3)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(jLabel12))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(interest2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agent1Combo)
                    .addComponent(Agent2Combo)
                    .addComponent(Agent3Combo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estimate1)
                    .addComponent(estimate2)
                    .addComponent(estimate3)
                    .addComponent(interest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interest3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agent5Combo)
                    .addComponent(Agent6Combo)
                    .addComponent(Agent4Combo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estimate6)
                            .addComponent(interest6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estimate4)
                            .addComponent(interest4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estimate5)
                            .addComponent(interest5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FormatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addComponent(StartButton)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        GuiEvent ge = new GuiEvent(this, 0);
        ge.addParameter(FormatCombo.getSelectedItem());
        ge.addParameter(estimate1.getText());
        ge.addParameter(estimate2.getText());
        ge.addParameter(estimate3.getText());
        ge.addParameter(estimate4.getText());
        ge.addParameter(estimate5.getText());
        ge.addParameter(estimate6.getText());
        ge.addParameter(Agent1Combo.getSelectedItem());
        ge.addParameter(Agent2Combo.getSelectedItem());
        ge.addParameter(Agent3Combo.getSelectedItem());
        ge.addParameter(Agent4Combo.getSelectedItem());
        ge.addParameter(Agent5Combo.getSelectedItem());
        ge.addParameter(Agent6Combo.getSelectedItem());
        ge.addParameter(interest1.getSelectedItem());
        ge.addParameter(interest2.getSelectedItem());
        ge.addParameter(interest3.getSelectedItem());
        ge.addParameter(interest4.getSelectedItem());
        ge.addParameter(interest5.getSelectedItem());
        ge.addParameter(interest6.getSelectedItem());
        
        myAgent.postGuiEvent(ge);
    }//GEN-LAST:event_StartButtonActionPerformed

    private void FormatComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormatComboActionPerformed
        String selectedFormat = (String) FormatCombo.getSelectedItem();
        switch (selectedFormat) {
            case "English":
                setAgentCombos(EnglishStrategies);
                break;
            case "Dutch":
                setAgentCombos(DutchStrategies);
                break;
            case "Scottish":
                setAgentCombos(ScottishStrategies);
                break;
            case "First-Price":
                setAgentCombos(FirstPriceStrategies);
                break;
            case "Vickrey":
                setAgentCombos(VickreyStrategies);
                break;
            case "Combo":
                setAgentCombos(ComboStrategies);
                break;
        }
                
        
    }//GEN-LAST:event_FormatComboActionPerformed

    private void estimate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estimate1ActionPerformed

    private void estimate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimate3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estimate3ActionPerformed

    private void estimate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimate4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estimate4ActionPerformed

    private void estimate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimate5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estimate5ActionPerformed

    private void estimate6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimate6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estimate6ActionPerformed
    
    private void setAgentCombos(String[] options) {
        Agent1Combo.setModel(new DefaultComboBoxModel(options));
        Agent2Combo.setModel(new DefaultComboBoxModel(options));
        Agent3Combo.setModel(new DefaultComboBoxModel(options));
        Agent4Combo.setModel(new DefaultComboBoxModel(options));
        Agent5Combo.setModel(new DefaultComboBoxModel(options));
        Agent6Combo.setModel(new DefaultComboBoxModel(options));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Agent1Combo;
    private javax.swing.JComboBox<String> Agent2Combo;
    private javax.swing.JComboBox<String> Agent3Combo;
    private javax.swing.JComboBox<String> Agent4Combo;
    private javax.swing.JComboBox<String> Agent5Combo;
    private javax.swing.JComboBox<String> Agent6Combo;
    private javax.swing.JComboBox<String> FormatCombo;
    private javax.swing.JButton StartButton;
    private javax.swing.JTextField estimate1;
    private javax.swing.JTextField estimate2;
    private javax.swing.JTextField estimate3;
    private javax.swing.JTextField estimate4;
    private javax.swing.JTextField estimate5;
    private javax.swing.JTextField estimate6;
    private javax.swing.JComboBox<String> interest1;
    private javax.swing.JComboBox<String> interest2;
    private javax.swing.JComboBox<String> interest3;
    private javax.swing.JComboBox<String> interest4;
    private javax.swing.JComboBox<String> interest5;
    private javax.swing.JComboBox<String> interest6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    // Set possible strategies per auction format
    final String[] EnglishStrategies = new String[]{"Default", "Collusion", "Shill"};
    final String[] DutchStrategies = new String[]{"Default", "Risk", "Informed"};
    final String[] ScottishStrategies = new String[]{"Impatient", "Patient", "Shill"};
    final String[] FirstPriceStrategies = new String[]{"Default", "Risk", "Informed"};
    final String[] VickreyStrategies = new String[]{"Default", "Malicious"};
    final String[] ComboStrategies = new String[]{"Default", "Risk"};
}
